sudo: required

# Tell travis we need docker service
services:
  - docker

# Specify command that should be running before deploy
before_install:
  - docker build -t martintoruan/docker-react -f Dockerfile.dev .

script:
  - docker run martintoruan/docker-react npm run test -- --coverage